//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : AppClass.sm
//

#ifndef APPCLASS_SM_H
#define APPCLASS_SM_H

#define _CRT_SECURE_NO_WARNINGS
#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class Map1;
class Map1_Start;
class Map1_c;
class Map1_r;
class Map1_e;
class Map1_a;
class Map1_t;
class Map1_First_Letter_JNM1;
class Map1_space_J;
class Map1_j;
class Map1_o;
class Map1_i;
class Map1_n;
class Map1_Sec_NM;
class Map1_First_Letter_JNM2;
class Map1_First_Letter_NM;
class Map1_List_Atr;
class Map1_First_Letter_AT;
class Map1_Comma;
class Map1_space_NM;
class Map1_EndBracket;
class Map1_OK;
class Map1_Error;
class Map1_Default;
class AppClassState;
class AppClassContext;
class AppClass;

class AppClassState :
    public statemap::State
{
public:

    AppClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(AppClassContext&) {};
    virtual void Exit(AppClassContext&) {};

    virtual void Alth(AppClassContext& context);
    virtual void Bracket_left(AppClassContext& context);
    virtual void Bracket_left_q(AppClassContext& context);
    virtual void Bracket_right(AppClassContext& context);
    virtual void Bracket_right_q(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
    virtual void Num(AppClassContext& context);
    virtual void Space(AppClassContext& context);
    virtual void Unknown(AppClassContext& context);
    virtual void W_Creat(AppClassContext& context);
    virtual void com(AppClassContext& context);
    virtual void eps(AppClassContext& context);

protected:

    virtual void Default(AppClassContext& context);
};

class Map1
{
public:

    static Map1_Start Start;
    static Map1_c c;
    static Map1_r r;
    static Map1_e e;
    static Map1_a a;
    static Map1_t t;
    static Map1_First_Letter_JNM1 First_Letter_JNM1;
    static Map1_space_J space_J;
    static Map1_j j;
    static Map1_o o;
    static Map1_i i;
    static Map1_n n;
    static Map1_Sec_NM Sec_NM;
    static Map1_First_Letter_JNM2 First_Letter_JNM2;
    static Map1_First_Letter_NM First_Letter_NM;
    static Map1_List_Atr List_Atr;
    static Map1_First_Letter_AT First_Letter_AT;
    static Map1_Comma Comma;
    static Map1_space_NM space_NM;
    static Map1_EndBracket EndBracket;
    static Map1_OK OK;
    static Map1_Error Error;
};

class Map1_Default :
    public AppClassState
{
public:

    Map1_Default(const char * const name, const int stateId)
    : AppClassState(name, stateId)
    {};

    virtual void W_Creat(AppClassContext& context);
    virtual void Unknown(AppClassContext& context);
    virtual void Alth(AppClassContext& context);
    virtual void Bracket_right(AppClassContext& context);
    virtual void Bracket_left(AppClassContext& context);
    virtual void Space(AppClassContext& context);
    virtual void com(AppClassContext& context);
    virtual void Num(AppClassContext& context);
    virtual void Bracket_right_q(AppClassContext& context);
    virtual void Bracket_left_q(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
};

class Map1_Start :
    public Map1_Default
{
public:
    Map1_Start(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
};

class Map1_c :
    public Map1_Default
{
public:
    Map1_c(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
};

class Map1_r :
    public Map1_Default
{
public:
    Map1_r(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
};

class Map1_e :
    public Map1_Default
{
public:
    Map1_e(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
};

class Map1_a :
    public Map1_Default
{
public:
    Map1_a(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
};

class Map1_t :
    public Map1_Default
{
public:
    Map1_t(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
    virtual void Space(AppClassContext& context);
};

class Map1_First_Letter_JNM1 :
    public Map1_Default
{
public:
    Map1_First_Letter_JNM1(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
    virtual void Num(AppClassContext& context);
    virtual void Space(AppClassContext& context);
};

class Map1_space_J :
    public Map1_Default
{
public:
    Map1_space_J(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Letter_j(AppClassContext& context);
};

class Map1_j :
    public Map1_Default
{
public:
    Map1_j(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Letter_o(AppClassContext& context);
};

class Map1_o :
    public Map1_Default
{
public:
    Map1_o(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Letter_i(AppClassContext& context);
};

class Map1_i :
    public Map1_Default
{
public:
    Map1_i(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Letter_n(AppClassContext& context);
};

class Map1_n :
    public Map1_Default
{
public:
    Map1_n(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Space(AppClassContext& context);
};

class Map1_Sec_NM :
    public Map1_Default
{
public:
    Map1_Sec_NM(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
};

class Map1_First_Letter_JNM2 :
    public Map1_Default
{
public:
    Map1_First_Letter_JNM2(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
    virtual void Num(AppClassContext& context);
};

class Map1_First_Letter_NM :
    public Map1_Default
{
public:
    Map1_First_Letter_NM(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void Bracket_right(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
    virtual void Num(AppClassContext& context);
    virtual void com(AppClassContext& context);
};

class Map1_List_Atr :
    public Map1_Default
{
public:
    Map1_List_Atr(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void Bracket_left(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
    virtual void com(AppClassContext& context);
};

class Map1_First_Letter_AT :
    public Map1_Default
{
public:
    Map1_First_Letter_AT(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void Bracket_left(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
    virtual void Num(AppClassContext& context);
    virtual void com(AppClassContext& context);
};

class Map1_Comma :
    public Map1_Default
{
public:
    Map1_Comma(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
};

class Map1_space_NM :
    public Map1_Default
{
public:
    Map1_space_NM(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Alth(AppClassContext& context);
    virtual void Bracket_left(AppClassContext& context);
    virtual void Bracket_right(AppClassContext& context);
    virtual void Letter_a(AppClassContext& context);
    virtual void Letter_c(AppClassContext& context);
    virtual void Letter_e(AppClassContext& context);
    virtual void Letter_i(AppClassContext& context);
    virtual void Letter_j(AppClassContext& context);
    virtual void Letter_n(AppClassContext& context);
    virtual void Letter_o(AppClassContext& context);
    virtual void Letter_r(AppClassContext& context);
    virtual void Letter_t(AppClassContext& context);
    virtual void Space(AppClassContext& context);
};

class Map1_EndBracket :
    public Map1_Default
{
public:
    Map1_EndBracket(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
};

class Map1_OK :
    public Map1_Default
{
public:
    Map1_OK(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void eps(AppClassContext& context);
};

class Map1_Error :
    public Map1_Default
{
public:
    Map1_Error(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
    virtual void eps(AppClassContext& context);
};

class AppClassContext :
    public statemap::FSMContext
{
public:

    explicit AppClassContext(AppClass& owner)
    : FSMContext(Map1::Start),
      _owner(owner)
    {};

    AppClassContext(AppClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline AppClass& getOwner()
    {
        return (_owner);
    };

    inline AppClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AppClassState&>(*_state);
    };

    inline void Alth()
    {
        getState().Alth(*this);
    };

    inline void Bracket_left()
    {
        getState().Bracket_left(*this);
    };

    inline void Bracket_left_q()
    {
        getState().Bracket_left_q(*this);
    };

    inline void Bracket_right()
    {
        getState().Bracket_right(*this);
    };

    inline void Bracket_right_q()
    {
        getState().Bracket_right_q(*this);
    };

    inline void EOS()
    {
        getState().EOS(*this);
    };

    inline void Letter_a()
    {
        getState().Letter_a(*this);
    };

    inline void Letter_c()
    {
        getState().Letter_c(*this);
    };

    inline void Letter_e()
    {
        getState().Letter_e(*this);
    };

    inline void Letter_i()
    {
        getState().Letter_i(*this);
    };

    inline void Letter_j()
    {
        getState().Letter_j(*this);
    };

    inline void Letter_n()
    {
        getState().Letter_n(*this);
    };

    inline void Letter_o()
    {
        getState().Letter_o(*this);
    };

    inline void Letter_r()
    {
        getState().Letter_r(*this);
    };

    inline void Letter_t()
    {
        getState().Letter_t(*this);
    };

    inline void Num()
    {
        getState().Num(*this);
    };

    inline void Space()
    {
        getState().Space(*this);
    };

    inline void Unknown()
    {
        getState().Unknown(*this);
    };

    inline void W_Creat()
    {
        getState().W_Creat(*this);
    };

    inline void com()
    {
        getState().com(*this);
    };

    inline void eps()
    {
        getState().eps(*this);
    };

private:
    AppClass& _owner;
};


#endif // APPCLASS_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
